.TH aws 1 "May 3, 2017"
.SH NAME
aws \- command-line interface to manage AWS services.
.SH SYNOPSIS
.B aws
[ options ] <command> <subcommand> [parameters]
.SH DESCRIPTION
This manual page briefly documents the
.B aws
command, a Command Line Interface (CLI) to manage Amazon web services (AWS).
.PP
.SH OPTIONS
Use
.I aws help
to display all options of
.B aws.
Help on commands/subcommands is also available via
.I aws <command> help
or
.I aws <command> <subcommand> help.
.SH SEE ALSO
.BR aws_completer (1),
.SH AUTHOR
aws was written by Amazon.com.
