.TH aws_completer 1 "May 3, 2017"
.SH NAME
aws_completer \- helper to enable completion for the aws CLI
.SH SYNOPSIS
.B aws_completer
.SH DESCRIPTION
.B aws_completer
is a helper program provided to enable shell completion for the
.B aws
CLI. It cannot be used on its own and supports the
.I bash
and
.I zsh
shell. Support for the available completion features is automatically
available, if general completion support is activated (e.g. by installing the
.I bash-completion
package) for bash or zsh.
.SH SEE ALSO
.BR aws (1)
.SH AUTHOR
aws_completer was written by Amazon.com.
